### ISSUE TITLE
Consider alternatives to breadboard connections

### ISSUE THREAD

**Issue by ashleyleal** [ashleyleal/resistor-vending-machine#4]
## Description
Breadboards provide very subpar connections and are very prone to various issues such as loose connections, electrical noise, and unstable connectivity. This can lead to unreliable circuit performance. For our final design, we should aim to use more permanent and stable prototyping methods such as soldered perfboards or custom printed circuit boards (PCBs).

## Task
- [x] Learn about soldered perfboards and custom PCBs
- [x] Decide whether a custom PCB design is feasible

## Resources
- [Arduino Prototyping Techniques #104: Perfboard](https://youtu.be/a3wDEcORRR4?si=g0dJylWgtog_BJBO)
- [From Solderless Breadboard to Soldered Circuit - Electronics with Becky Stern | Digi-Key Electronics](https://youtu.be/F9Krq7seV1g?si=3E-IcG6oC-kamMFo)
- [From Idea to Schematic to PCB - How to do it easily!](https://youtu.be/35YuILUlfGs?si=q-QTpj53MdX78AZd)
- Geoffrey's Altium Workshop

**Comment by ashleyleal** [comment]
Good work ser

**Comment by AthavanBalakumar** [comment]
thank you my goat
