### ISSUE TITLE
Resistor roll jamming

### ISSUE THREAD

**Issue by ashleyleal** [ashleyleal/resistor-vending-machine#6]
i will write this description tomorrow

**Comment by GeoFryer** [comment]
tomorrow is now today vro

anyways let me know if you think i should machine the part instead (i have no way of doing this, but if it's better than I shall try). Or maybe i'll just buy a shaft collar that is machined and put the oring around that

lmk if the problem is from something else tho

**Comment by ashleyleal** [comment]
fixed

**Comment by ashleyleal** [comment]
Problem was with assembly lmao i noticed measurements between bearing holder and shaft collar weren't symmetric on both sides so i just adjusted the position of the shaft collar a bit which got rid of the problem of resistor roll skewing to one side and jamming
